export const GET_TENANT_QUESTIONS_REQUEST = 'GET_TENANT_QUESTIONS_REQUEST';
export const GET_TENANT_QUESTIONS_SUCCESS = 'GET_TENANT_QUESTIONS_SUCCESS';
export const GET_TENANT_QUESTIONS_FAILURE = 'GET_TENANT_QUESTIONS_FAILURE';

export const getTenanTQuestionsRequest = payload => ({
  type: GET_TENANT_QUESTIONS_REQUEST,
  payload,
});

