export const GET_ENTITY_QUESTIONS_REQUEST = 'GET_ENTITY_QUESTIONS_REQUEST';
export const GET_ENTITY_QUESTIONS_SUCCESS = 'GET_ENTITY_QUESTIONS_SUCCESS';
export const GET_ENTITY_QUESTIONS_FAILURE = 'GET_ENTITY_QUESTIONS_FAILURE';

export const getEntityQuestionsRequest = payload => ({
  type: GET_ENTITY_QUESTIONS_REQUEST,
  payload,
});

