export const GET_ENTITY_NOTIFICATIONS_REQUEST = 'GET_ENTITY_NOTIFICATIONS_REQUEST';
export const GET_ENTITY_NOTIFICATIONS_SUCCESS = 'GET_ENTITY_NOTIFICATIONS_SUCCESS';
export const GET_ENTITY_NOTIFICATIONS_FAILURE = 'GET_ENTITY_NOTIFICATIONS_FAILURE';

export const getEntityNotificationsRequest = payload => ({
  type: GET_ENTITY_NOTIFICATIONS_REQUEST,
  payload,
});

