export const GET_ENTITY_NOTIFICATIONS_REQUEST = 'GET_ENTITY_NOTIFICATIONS_REQUEST';
export const GET_ENTITY_NOTIFICATIONS_SUCCESS = 'GET_ENTITY_NOTIFICATIONS_SUCCESS';
export const GET_ENTITY_NOTIFICATIONS_FAILURE = 'GET_ENTITY_NOTIFICATIONS_FAILURE';

export const MARK_AS_READ_NOTIFICATION_REQUEST = 'MARK_AS_READ_NOTIFICATION_REQUEST';
export const MARK_AS_READ_NOTIFICATION_SUCCESS = 'MARK_AS_READ_NOTIFICATION_SUCCESS';
export const MARK_AS_READ_NOTIFICATION_FAILURE = 'MARK_AS_READ_NOTIFICATION_FAILURE';

export const getEntityNotificationsRequest = payload => ({
  type: GET_ENTITY_NOTIFICATIONS_REQUEST,
  payload,
});

export const markAsReadNotificationRequest = payload => ({
  type: MARK_AS_READ_NOTIFICATION_REQUEST,
  payload,
});

